// when an exception is thrown by a catch block to another catch block, the process is known as
// Rethrowing exception

// Syntax

try {
  // code
} catch(data){
  throw;
}
